language: node_js
sudo: false
node_js:
  - 4
  - 5
cache:
  directories:
      - node_modules
after_script:
  - npm run cov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b98f41fd6ac7d5740632
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
