language: node_js

node_js:
  - 4
  - 5
  - 6
  - 7

script:
  - npm test

after_script:
  - npm run coverage
  - npm run publish-coverage

cache:
  directories:
      - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b98f41fd6ac7d5740632
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

addons:
    code_climate:
        repo_token: 3c36669d9ab34d1a5216c313a883c7bb29813c806fdfe35d8a05c7ff5c692279